# Generated by Django 6.0.3 on 2026-04-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_students_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=100)),
                ('emp_email', models.CharField(max_length=100)),
                ('emp_code', models.CharField(max_length=100)),
                ('emp_phone', models.CharField(max_length=100)),
                ('emp_designation', models.CharField(max_length=100)),
                ('emp_salary', models.CharField(max_length=100)),
                ('emp_address', models.CharField(max_length=100)),
            ],
        ),
    ]
