# Generated by Django 6.0.3 on 2026-04-12 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_department',
            field=models.CharField(default='IT', max_length=100),
        ),
    ]
